# ============================================================================
# Chart Style Template
# Generated by chart-style-extractor skill
# Source: [SOURCE_IMAGE_DESCRIPTION]
# ============================================================================

library(ggplot2)

# ============================================================================
# COLOR PALETTE
# ============================================================================
colors_extracted <- c(
  "#color1",  # Primary color
  "#color2",  # Secondary color
  "#color3",  # Tertiary color
  "#color4"   # Quaternary color
)

scale_fill_extracted <- scale_fill_manual(values = colors_extracted)
scale_color_extracted <- scale_color_manual(values = colors_extracted)

# ============================================================================
# THEME
# ============================================================================
theme_extracted <- theme_bw() +  # Base theme
  theme(
    # Text elements
    text = element_text(family = "sans"),
    plot.title = element_text(size = 14, face = "bold", hjust = 0),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    
    # Panel
    panel.grid.major = element_line(color = "grey90", linewidth = 0.2),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white", color = NA),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    
    # Axes
    axis.line = element_line(color = "black", linewidth = 0.3),
    axis.ticks = element_line(color = "black", linewidth = 0.3),
    
    # Legend
    legend.position = "top",
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9),
    
    # Strips (for facets)
    strip.background = element_rect(fill = "grey95"),
    strip.text = element_text(size = 10, face = "bold")
  )

# ============================================================================
# EXAMPLE USAGE
# ============================================================================

# Mock data for demonstration
df_mock <- data.frame(
  category = rep(c("Group A", "Group B", "Group C"), each = 2),
  condition = rep(c("Control", "Treatment"), times = 3),
  value = c(10, 15, 25, 30, 18, 22)
)

# Create example plot
p_example <- ggplot(df_mock, aes(x = category, y = value, fill = condition)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  scale_fill_extracted +
  theme_extracted +
  labs(
    title = "Example Chart with Extracted Style",
    x = "Category",
    y = "Value",
    fill = "Condition"
  )

# Display plot
print(p_example)

# Save plot
ggsave("example_plot.png", p_example, width = 8, height = 5, dpi = 300)

cat("Style template loaded successfully!\n")
cat("Use: scale_fill_extracted, scale_color_extracted, theme_extracted\n")
